# Generated by Django 3.0.4 on 2020-03-30 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jolybell', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('full_price', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_delivered', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('IPM', 'In process of making'), ('INS', 'In stock'), ('IND', 'In delivery'), ('IPO', 'In your post office')], default='IPM', max_length=3)),
                ('delivered', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='jolybell.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
