# Generated by Django 3.0.4 on 2020-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jolybell', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In process of making', 'IPM'), ('In stock', 'INS'), ('In delivery', 'IND'), ('In your post office', 'IPO')], default='IPM', max_length=50),
        ),
    ]
